
default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: accounter
  username: jorge
  password: 123451

test:
  <<: *default
  database: accounter_test



production:
  url: <%= ENV['DATABASE_URL'] %>